// World of Shoegaze — band data
// Extracted from the source explorer. Loaded as a plain global.

window.WOS_DATA = (function () {
  const MOOD_COLORS = {
    euphoric_bliss: { hue: 340, label: "euphoric bliss", desc: "Classic dreamy wall-of-sound" },
    ethereal_celestial: { hue: 200, label: "ethereal celestial", desc: "Voices from another plane" },
    noisy_chaotic: { hue: 15, label: "noisy chaotic", desc: "Beauty buried in feedback" },
    dark_gothic: { hue: 280, label: "dark gothic", desc: "Dream pop with teeth" },
    psychedelic_hypnotic: { hue: 50, label: "psychedelic hypnotic", desc: "Drone, repetition, trance" },
    wistful_dreamers: { hue: 260, label: "wistful dreamers", desc: "Gaze with the volume turned down" },
    yearning_anthemic: { hue: 25, label: "yearning anthemic", desc: "Big choruses, post-hardcore heart" },
    hypnotic_heavy: { hue: 220, label: "hypnotic heavy", desc: "Slow tempos, dense low end" },
    depressive_beauty: { hue: 250, label: "depressive beauty", desc: "Pretty melodies wrapped in despair" },
    ecstatic_catharsis: { hue: 320, label: "ecstatic catharsis", desc: "Euphoric noise" },
    apocalyptic_doom: { hue: 0, label: "apocalyptic doom", desc: "End-of-world heaviness" },
    muscular_brooding: { hue: 210, label: "muscular brooding", desc: "Controlled aggression" },
    volatile_violent: { hue: 355, label: "volatile violent", desc: "Beauty interrupted" },
    sun_bleached_sludge: { hue: 35, label: "sun-bleached sludge", desc: "Sludgy 90s alt weariness" },
    modern_anguish: { hue: 310, label: "modern anguish", desc: "Current scene angst" },
    dream_pop_warmth: { hue: 20, label: "dream pop warmth", desc: "Warm, melodic, accessible" },
    lo_fi_bedroom: { hue: 40, label: "lo-fi bedroom", desc: "Homemade, distant, intimate" },
    ambient_drift: { hue: 190, label: "ambient drift", desc: "Near-formless atmosphere" },
    nostalgic_jangly: { hue: 55, label: "nostalgic jangly", desc: "Twee, noise-pop adjacent" },
    experimental_strange: { hue: 170, label: "experimental strange", desc: "Hard to pin down" },
    japanese_gaze: { hue: 335, label: "Japanese gaze", desc: "Japan's sweet-meets-aggressive tradition" },
  };

  const MOOD_TO_BANDS = {
    euphoric_bliss: ["My Bloody Valentine", "Slowdive", "Ride", "Lush", "Chapterhouse", "Pale Saints", "Ringo Deathstarr", "Amusement Parks on Fire", "Westkust", "Pia Fraus", "Air Formation"],
    ethereal_celestial: ["Cocteau Twins", "This Mortal Coil", "Sun's Signature", "Mojave 3"],
    noisy_chaotic: ["The Jesus and Mary Chain", "A Place to Bury Strangers", "Whirr", "Medicine", "Serena-Maneesh", "No Joy", "Lovesliescrushing"],
    dark_gothic: ["Curve", "The Cranes", "Mazzy Star", "Tamaryn", "Lowlife", "Crystal Stilts"],
    psychedelic_hypnotic: ["Spacemen 3", "Loop", "Spiritualized", "The Telescopes", "Flying Saucer Attack"],
    wistful_dreamers: ["Title Fight", "Turnover", "Basement", "Webbed Wing", "Beach Fossils", "Hibou", "Wild Nothing"],
    yearning_anthemic: ["Citizen", "Balance and Composure", "Far", "Anxious", "Koyo", "Adorable"],
    hypnotic_heavy: ["Hum", "Cloakroom", "True Widow", "Failure", "Catherine Wheel", "Swervedriver"],
    depressive_beauty: ["Nothing", "Alcest", "Lantlôs", "Have a Nice Life", "Knifeplay", "Cigarettes After Sex"],
    ecstatic_catharsis: ["Deafheaven", "Astronoid", "Fleshwater"],
    apocalyptic_doom: ["Greet Death", "Holy Fawn", "Spotlights", "Bosse-de-Nage", "Jesu", "Sadness", "An Autumn for Crippled Children", "Amesoeurs"],
    muscular_brooding: ["Narrow Head", "Quicksand", "Cave In", "The Boo Radleys", "Moose"],
    volatile_violent: ["Loathe", "Spiritbox"],
    sun_bleached_sludge: ["Superheaven", "The Verve"],
    modern_anguish: ["Glare", "Glixen", "Julie", "Wisp", "Feeble Little Horse"],
    dream_pop_warmth: ["Beach House", "M83", "DIIV", "Asobi Seksu", "Drop Nineteens", "Galaxie 500", "Engineers", "Cheatahs"],
    lo_fi_bedroom: ["Parannoul", "Asian Glow", "Quannnic", "Hotline TNT", "Sonhos Tomam Conta", "bdrmm", "My Dead Girlfriend"],
    ambient_drift: ["Auburn Lull", "Bowery Electric", "Ulrich Schnauss", "Half String"],
    nostalgic_jangly: ["Black Tambourine", "Velocity Girl", "The Pains of Being Pure at Heart", "Lilys", "The Radio Dept.", "Yuck", "For Tracy Hyde"],
    experimental_strange: ["They Are Gutting a Body of Water", "Coaltar of the Deepers", "Sweet Trip", "Bilmuri"],
    japanese_gaze: ["Kinoko Teikoku", "For Tracy Hyde", "My Dead Girlfriend", "Coaltar of the Deepers", "Cruyff in the Bedroom", "Plastic Girl in Closet", "Tokyo Shoegazer"],
  };

  // [name, subgenre, country, era, album, year, intensity, lat, lng]
  const RAW = [
    ["My Bloody Valentine", "shoegaze", "Ireland/UK", "first_wave", "Loveless", 1991, 6, 53.35, -6.26],
    ["Slowdive", "shoegaze", "UK", "first_wave", "Souvlaki", 1993, 4, 51.46, -1.07],
    ["Ride", "shoegaze", "UK", "first_wave", "Nowhere", 1990, 5, 51.75, -1.26],
    ["Cocteau Twins", "dream pop / proto-shoegaze", "UK", "proto", "Heaven or Las Vegas", 1990, 3, 55.95, -3.19],
    ["The Jesus and Mary Chain", "noise pop", "UK", "proto", "Psychocandy", 1985, 6, 55.86, -4.25],
    ["Lush", "shoegaze / dream pop", "UK", "first_wave", "Spooky", 1992, 4, 51.5, -0.12],
    ["Swervedriver", "shoegaze", "UK", "first_wave", "Mezcal Head", 1993, 6, 51.75, -1.26],
    ["Hum", "alt-rock / heavy gaze", "USA", "transitional", "You'd Prefer an Astronaut", 1995, 6, 40.11, -88.21],
    ["Chapterhouse", "shoegaze", "UK", "first_wave", "Whirlpool", 1991, 4, 51.46, -0.97],
    ["Catherine Wheel", "shoegaze", "UK", "first_wave", "Ferment", 1992, 6, 52.63, 1.29],
    ["Pale Saints", "shoegaze / dream pop", "UK", "first_wave", "The Comforts of Madness", 1990, 4, 53.8, -1.55],
    ["Curve", "shoegaze / industrial", "UK", "first_wave", "Doppelgänger", 1992, 6, 51.5, -0.12],
    ["Medicine", "shoegaze", "USA", "first_wave", "Shot Forth Self Living", 1992, 7, 34.05, -118.24],
    ["Drop Nineteens", "shoegaze", "USA", "first_wave", "Delaware", 1992, 5, 42.36, -71.06],
    ["Mazzy Star", "dream pop", "USA", "first_wave", "So Tonight That I Might See", 1993, 3, 34.05, -118.24],
    ["Mojave 3", "dream folk", "UK", "transitional", "Ask Me Tomorrow", 1995, 2, 51.46, -1.07],
    ["Spacemen 3", "psych / proto-gaze", "UK", "proto", "Playing with Fire", 1989, 4, 52.51, -1.46],
    ["The Telescopes", "noise-gaze / psych", "UK", "proto", "Taste", 1989, 7, 53.38, -1.47],
    ["Galaxie 500", "dream pop / slowcore", "USA", "proto", "On Fire", 1989, 2, 42.36, -71.06],
    ["Spiritualized", "space rock / gospel", "UK", "transitional", "Ladies and Gentlemen We Are Floating in Space", 1997, 5, 51.5, -0.12],
    ["Loop", "drone / psych", "UK", "proto", "Heaven's End", 1987, 6, 51.5, -0.12],
    ["The Verve", "shoegaze / space rock", "UK", "first_wave", "A Storm in Heaven", 1993, 5, 53.55, -2.27],
    ["Moose", "shoegaze", "UK", "first_wave", "...XYZ", 1992, 5, 51.5, -0.12],
    ["Adorable", "shoegaze / indie rock", "UK", "first_wave", "Against Perfection", 1993, 5, 52.41, -1.51],
    ["The Boo Radleys", "shoegaze / indie pop", "UK", "first_wave", "Giant Steps", 1993, 5, 53.4, -2.99],
    ["M83", "dream pop / electronic gaze", "France", "second_wave", "Dead Cities, Red Seas & Lost Ghosts", 2003, 5, 43.71, 7.26],
    ["Asobi Seksu", "shoegaze / dream pop", "USA", "second_wave", "Citrus", 2006, 5, 40.71, -74.0],
    ["A Place to Bury Strangers", "noise-gaze", "USA", "second_wave", "A Place to Bury Strangers", 2007, 8, 40.71, -74.0],
    ["DIIV", "indie / dream pop", "USA", "second_wave", "Oshin", 2012, 4, 40.71, -74.0],
    ["Beach House", "dream pop", "USA", "second_wave", "Teen Dream", 2010, 3, 39.29, -76.61],
    ["Whirr", "noise-gaze", "USA", "second_wave", "Sway", 2014, 7, 37.77, -122.41],
    ["Nothing", "shoegaze (hardcore lineage)", "USA", "second_wave", "Guilty of Everything", 2014, 6, 39.95, -75.16],
    ["Deafheaven", "blackgaze", "USA", "second_wave", "Sunbather", 2013, 9, 37.77, -122.41],
    ["Alcest", "blackgaze / post-metal", "France", "second_wave", "Souvenirs d'un autre monde", 2007, 5, 48.85, 2.35],
    ["Wisp", "modern shoegaze", "USA", "current", "Pandora", 2024, 4, 37.77, -122.41],
    ["Lilys", "shoegaze / indie pop", "USA", "first_wave", "In the Presence of Nothing", 1992, 5, 38.9, -77.04],
    ["Velocity Girl", "noise pop / shoegaze", "USA", "first_wave", "Copacetic", 1993, 5, 38.9, -77.04],
    ["Bowery Electric", "dream pop / trip-hop gaze", "USA", "transitional", "Beat", 1996, 4, 40.71, -74.0],
    ["Flying Saucer Attack", "lo-fi space gaze", "UK", "transitional", "Further", 1995, 4, 51.45, -2.58],
    ["Sweet Trip", "electronic gaze / glitch pop", "USA", "transitional", "Velocity:Design:Comfort", 2003, 5, 37.77, -122.41],
    ["Lovesliescrushing", "drone / noise gaze", "USA", "first_wave", "Bloweyelashwish", 1993, 5, 41.49, -81.69],
    ["Auburn Lull", "ambient gaze", "USA", "transitional", "Alone I Admire", 1999, 3, 42.73, -84.55],
    ["Half String", "shoegaze", "USA", "transitional", "A Fascination with Heights", 1996, 4, 33.44, -112.07],
    ["Failure", "space rock / alt-gaze", "USA", "transitional", "Fantastic Planet", 1996, 5, 34.05, -118.24],
    ["Jesu", "shoegaze metal", "UK", "second_wave", "Conqueror", 2007, 8, 52.48, -1.9],
    ["The Pains of Being Pure at Heart", "indie pop / gaze", "USA", "second_wave", "The Pains of Being Pure at Heart", 2009, 4, 40.71, -74.0],
    ["The Radio Dept.", "indie pop / dream pop", "Sweden", "second_wave", "Lesser Matters", 2003, 3, 55.6, 13.0],
    ["Engineers", "dreamy gaze / post-rock", "UK", "second_wave", "Engineers", 2005, 4, 51.5, -0.12],
    ["Serena-Maneesh", "noise-gaze / psych", "Norway", "second_wave", "Serena-Maneesh", 2005, 6, 59.91, 10.75],
    ["Ulrich Schnauss", "electronic / ambient gaze", "Germany", "second_wave", "A Strangely Isolated Place", 2003, 3, 52.52, 13.4],
    ["Amusement Parks on Fire", "shoegaze", "UK", "second_wave", "Amusement Parks on Fire", 2004, 5, 52.95, -1.15],
    ["Wild Nothing", "dream pop", "USA", "second_wave", "Gemini", 2010, 3, 37.23, -80.41],
    ["No Joy", "noise-gaze", "Canada", "second_wave", "More Faithful", 2015, 6, 45.5, -73.56],
    ["Ringo Deathstarr", "shoegaze", "USA", "second_wave", "Colour Trip", 2011, 6, 30.26, -97.74],
    ["Cloakroom", "stonegaze / heavy gaze", "USA", "current", "Time Well", 2017, 6, 41.46, -87.06],
    ["Have a Nice Life", "post-punk / drone gaze", "USA", "second_wave", "Deathconsciousness", 2008, 7, 41.76, -72.67],
    ["Tamaryn", "dark gaze / dream pop", "New Zealand/USA", "second_wave", "The Waves", 2010, 5, 37.77, -122.41],
    ["Beach Fossils", "indie / dream pop", "USA", "second_wave", "Clash the Truth", 2013, 3, 40.71, -74.0],
    ["Cheatahs", "shoegaze / krautgaze", "UK", "second_wave", "Cheatahs", 2014, 5, 51.5, -0.12],
    ["Yuck", "indie rock / 90s revival", "UK", "second_wave", "Yuck", 2011, 5, 51.5, -0.12],
    ["Crystal Stilts", "post-punk / dream pop", "USA", "second_wave", "Alight of Night", 2008, 4, 40.71, -74.0],
    ["Black Tambourine", "noise pop / twee", "USA", "proto", "Black Tambourine", 2010, 5, 38.9, -77.04],
    ["Kinoko Teikoku", "Japanese shoegaze", "Japan", "second_wave", "eureka", 2013, 5, 35.68, 139.69],
    ["For Tracy Hyde", "Japanese dream pop / gaze", "Japan", "current", "ethernity", 2017, 4, 35.68, 139.69],
    ["My Dead Girlfriend", "Japanese shoegaze", "Japan", "second_wave", "Hatsukoi", 2010, 4, 35.68, 139.69],
    ["Coaltar of the Deepers", "Japanese eclectic gaze", "Japan", "transitional", "No Thank You", 2002, 7, 35.68, 139.69],
    ["Cruyff in the Bedroom", "Japanese shoegaze", "Japan", "transitional", "Hello", 2003, 5, 35.68, 139.69],
    ["Plastic Girl in Closet", "Japanese shoegaze", "Japan", "second_wave", "This is My Shoegazer", 2010, 4, 35.68, 139.69],
    ["Tokyo Shoegazer", "Japanese shoegaze", "Japan", "second_wave", "Crystallize", 2011, 5, 35.68, 139.69],
    ["Julie", "heavy shoegaze", "USA", "current", "my anti-aircraft friend", 2024, 7, 34.05, -118.24],
    ["They Are Gutting a Body of Water", "experimental shoegaze", "USA", "current", "Lucky Styles", 2022, 6, 39.95, -75.16],
    ["Parannoul", "lo-fi shoegaze", "South Korea", "current", "To See the Next Part of the Dream", 2021, 5, 37.57, 126.98],
    ["Asian Glow", "lo-fi shoegaze / emo", "South Korea", "current", "Cull Ficle", 2021, 6, 37.57, 126.98],
    ["Sonhos Tomam Conta", "lo-fi shoegaze", "Brazil", "current", "Sonhos Tomam Conta", 2022, 4, -23.55, -46.63],
    ["Knifeplay", "slowcore / gaze", "USA", "current", "Animal Drowning", 2022, 4, 39.95, -75.16],
    ["Feeble Little Horse", "noise pop / gaze", "USA", "current", "Girl with Fish", 2023, 5, 40.44, -79.99],
    ["Glixen", "modern shoegaze", "USA", "current", "She Only Said", 2023, 5, 33.44, -112.07],
    ["Glare", "modern shoegaze", "USA", "current", "The Beauty of the End", 2024, 7, 29.76, -95.36],
    ["Quannnic", "bedroom shoegaze", "USA", "current", "Stepdream", 2022, 5, 40.71, -74.0],
    ["Fleshwater", "metalcore-gaze", "USA", "current", "We're Not Here to Be Loved", 2022, 7, 42.36, -71.06],
    ["Greet Death", "doomgaze", "USA", "current", "New Hell", 2019, 7, 43.0, -83.69],
    ["Narrow Head", "grunge-gaze", "USA", "current", "12th House Rock", 2020, 7, 29.76, -95.36],
    ["Hotline TNT", "lo-fi gaze / power pop", "USA", "current", "Cartwheel", 2023, 5, 40.71, -74.0],
    ["bdrmm", "modern shoegaze", "UK", "current", "Bedroom", 2020, 5, 53.74, -0.33],
    ["Mint Field", "psych-gaze", "Mexico", "current", "Pasar de las Luces", 2018, 4, 19.43, -99.13],
    ["Westkust", "shoegaze / dream pop", "Sweden", "second_wave", "Last Forever", 2015, 5, 57.71, 11.97],
    ["The Cranes", "dark dream pop", "UK", "first_wave", "Forever", 1993, 5, 50.91, -1.4],
    ["Lowlife", "post-punk / dream pop", "UK", "proto", "Permanent Sleep", 1986, 4, 55.95, -3.19],
    ["This Mortal Coil", "4AD dream pop", "UK", "proto", "It'll End in Tears", 1984, 3, 51.5, -0.12],
    ["Sun's Signature", "dream pop", "UK", "current", "Sun's Signature", 2022, 3, 55.95, -3.19],
    ["Cigarettes After Sex", "dream pop / sadcore", "USA", "current", "Cigarettes After Sex", 2017, 3, 31.76, -106.49],
    ["Sadness", "blackgaze / depressive black metal", "USA", "current", "Atna", 2021, 8, 47.6, -122.33],
    ["An Autumn for Crippled Children", "blackgaze", "Netherlands", "second_wave", "Try Not to Destroy Everything You Love", 2015, 7, 52.37, 4.9],
    ["Lantlôs", "blackgaze / post-everything", "Germany", "second_wave", "Melting Sun", 2014, 7, 50.94, 6.96],
    ["Amesoeurs", "blackgaze / post-punk", "France", "second_wave", "Amesoeurs", 2009, 7, 48.85, 2.35],
    ["Astronoid", "dream-thrash / blackgaze-adjacent", "USA", "current", "Air", 2016, 6, 42.36, -71.06],
    ["Air Formation", "shoegaze", "UK", "second_wave", "Daylight Storms", 2006, 5, 50.82, -0.13],
    ["Resplandor", "shoegaze", "Peru", "second_wave", "Pan-American Saint", 2009, 4, -12.04, -77.04],
    ["Pia Fraus", "shoegaze / twee", "Estonia", "transitional", "In Solarium", 2002, 4, 59.43, 24.75],
    ["Hibou", "dream pop / surf gaze", "USA", "second_wave", "Hibou", 2015, 3, 47.6, -122.33],
    ["Title Fight", "post-hardcore → shoegaze", "USA", "current", "Hyperview", 2015, 4, 41.24, -75.88],
    ["Citizen", "post-hardcore / emo-gaze", "USA", "current", "Everybody Is Going to Heaven", 2015, 5, 41.66, -83.58],
    ["Turnover", "pop-punk → dream pop", "USA", "current", "Peripheral Vision", 2015, 2, 36.85, -76.29],
    ["Basement", "post-hardcore / emo-gaze", "UK", "second_wave", "Colourmeinkindness", 2012, 4, 52.63, 1.29],
    ["Balance and Composure", "post-hardcore / emo-gaze", "USA", "second_wave", "The Things We Think We're Missing", 2013, 5, 40.6, -75.47],
    ["Superheaven", "grunge-gaze / sludgy alt", "USA", "current", "Jar", 2013, 6, 39.95, -75.16],
    ["True Widow", "stonegaze", "USA", "second_wave", "Circumambulation", 2013, 6, 32.78, -96.8],
    ["Holy Fawn", "post-metal / atmospheric heavy", "USA", "current", "Death Spells", 2018, 7, 33.44, -112.07],
    ["Spotlights", "post-metal / doomgaze", "USA", "current", "Tidals", 2017, 8, 40.71, -74.0],
    ["Loathe", "metalcore × shoegaze", "UK", "current", "I Let It In and It Took Everything", 2020, 9, 53.4, -2.99],
    ["Spiritbox", "metalcore with gaze textures", "Canada", "current", "Eternal Blue", 2021, 9, 48.43, -123.37],
    ["Bilmuri", "post-metalcore / genre-blender", "USA", "current", "AMERICAN MOTOR SPORTS", 2024, 7, 41.5, -81.69],
    ["Bosse-de-Nage", "blackgaze / experimental", "USA", "second_wave", "III", 2012, 8, 37.77, -122.41],
    ["Quicksand", "post-hardcore", "USA", "first_wave", "Slip", 1993, 7, 40.71, -74.0],
    ["Cave In", "post-hardcore / space rock", "USA", "transitional", "Jupiter", 2000, 7, 42.36, -71.06],
    ["Far", "post-hardcore / emo", "USA", "transitional", "Water and Solutions", 1998, 6, 38.58, -121.49],
    ["Webbed Wing", "indie-gaze / scrappy alt", "USA", "current", "What's So Fucking Funny", 2020, 5, 39.95, -75.16],
    ["Anxious", "emo / gaze-adjacent", "USA", "current", "Little Green House", 2022, 5, 41.18, -73.18],
    ["Koyo", "emo / post-hardcore", "USA", "current", "Would You Miss It?", 2024, 5, 40.78, -73.13],
  ];

  // Short descriptions for cards/details. Only critical ones; rest get a derived one.
  const DESC = {
    "My Bloody Valentine": "The genre's center of gravity. Kevin Shields' guitar manipulations on Loveless became the template for everything after.",
    "Slowdive": "The most emotionally resonant of the originals — ethereal, melancholy, patient.",
    "Ride": "Oxford four-piece whose Nowhere is a foundational text — propulsive, melodic, kinetic.",
    "Cocteau Twins": "Liz Fraser's glossolalia and Robin Guthrie's effects-drenched guitars laid the entire blueprint.",
    "The Jesus and Mary Chain": "Psychocandy invented the feedback-pop hybrid that shoegaze would refine.",
    "Lush": "Sharper, more pop-forward songwriting than most of their scene peers.",
    "Swervedriver": "The muscular, motorik, road-tripping end of the scene.",
    "Hum": "Illinois band whose 90s records and 2020 reunion defined the heavy-melodic blueprint everyone is now copying.",
    "Chapterhouse": "Whirlpool is criminally underrated — dance-leaning, sparkling shoegaze.",
    "Catherine Wheel": "Heavier and more rock-leaning — guitar muscle with a gaze veneer.",
    "Pale Saints": "Leeds band that was beautifully strange — fractured pop with a 4AD sensibility.",
    "Curve": "Darker, more electronic and gothic than most of the scene.",
    "Medicine": "The great American answer to MBV — noisier, brattier, more deranged.",
    "Drop Nineteens": "Boston band whose Delaware is a cult classic — slacker-y, dreamy, deceptively heavy.",
    "Mazzy Star": "Hope Sandoval's voice over David Roback's haunted Americana — desert dream pop.",
    "Spacemen 3": "Drugs, drone, repetition — the spiritual ancestor of shoegaze's hypnotic side.",
    "Deafheaven": "Bay Area band whose 2013 album fused black metal blast beats with shoegaze euphoria.",
    "Alcest": "Neige's project — foundational blackgaze, leaning more dreamy than aggressive.",
    "Wisp": "The TikTok-era breakthrough — gauzy, intimate gaze for a new generation.",
    "Parannoul": "Anonymous Korean bedroom artist whose 2021 album became an internet phenomenon.",
    "Have a Nice Life": "Bedroom-recorded double album that became a cult phenomenon — bleak, vast, devastating.",
    "Nothing": "Philadelphia band founded by ex-hardcore members; lush, beautiful, often harrowing.",
    "Beach House": "Baltimore duo perfecting the slow-build, organ-and-guitar dream pop format.",
    "A Place to Bury Strangers": "Marketed as the loudest band in NYC — abrasive, industrial, relentless.",
    "Galaxie 500": "Boston trio whose slow, fragile records were proto-everything-good.",
    "Julie": "LA band channeling Nothing/Deftones heaviness with magnetic vocal interplay.",
    "Loathe": "Liverpool band that perfected the Deftones-meets-MBV formula on their 2020 breakthrough.",
    "DIIV": "The flagship indie-gaze band of the 2010s, evolving toward heavier post-shoegaze.",
    "Asobi Seksu": "NYC band whose Citrus defined the 2000s revival — bilingual, sugary, propulsive.",
    "Glare": "Texas band part of the current heavy-gaze revival; emotionally raw and abrasive.",
    "For Tracy Hyde": "Bittersweet, hyper-melodic J-gaze named after a British actress.",
    "Kinoko Teikoku": "Tokyo band moving from heavy gaze to dreamy J-pop across their run.",
    "Coaltar of the Deepers": "Genre-omnivorous Japanese project — gaze, metal, anime themes, drum 'n' bass.",
    "M83": "Anthony Gonzalez's early albums were pure cathedral-of-sound shoegaze.",
    "Mojave 3": "Slowdive members going pastoral after the gaze imploded.",
    "Spiritualized": "Jason Pierce's post-Spacemen 3 vehicle — symphonic, addictive, ecstatic.",
    "Sun's Signature": "Liz Fraser's long-awaited return — radiant, voice-as-instrument dream pop.",
    "This Mortal Coil": "Ivo Watts-Russell's 4AD supergroup of darkly beautiful covers and originals.",
  };

  const BANDS = RAW.map(([name, subgenre, country, era, album, year, intensity, lat, lng]) => ({
    name, subgenre, country, era, album, year, intensity, lat, lng,
    desc: DESC[name] || `${subgenre} — ${country}, ${year}.`,
  }));

  const BAND_MOODS = {};
  Object.entries(MOOD_TO_BANDS).forEach(([mood, names]) => {
    names.forEach(n => { (BAND_MOODS[n] ||= []).push(mood); });
  });

  const ERAS = [
    { key: "proto", label: "Proto", range: "pre-1989" },
    { key: "first_wave", label: "First Wave", range: "1989–94" },
    { key: "transitional", label: "Transitional", range: "1995–2003" },
    { key: "second_wave", label: "Nu-Gaze", range: "2004–13" },
    { key: "current", label: "Current", range: "2014–now" },
  ];

  // Scene reports for the globe sidebar
  const SCENES = [
    { city: "Tokyo", country: "Japan", lat: 35.68, lng: 139.69, era: "second_wave", note: "A parallel evolution — sweeter melodies, sharper noise. The world's most loyal scene." },
    { city: "Seoul", country: "South Korea", lat: 37.57, lng: 126.98, era: "current", note: "Post-2020 bedroom explosion. Anonymous teens making the most-listened-to gaze on the internet." },
    { city: "Thames Valley", country: "UK", lat: 51.46, lng: -1.07, era: "first_wave", note: "Reading, Oxford, Slough — the constellation of late-80s ghosts. Where it was invented." },
    { city: "Philadelphia", country: "USA", lat: 39.95, lng: -75.16, era: "current", note: "Hardcore kids who decided to be pretty. Nothing, Knifeplay, TAGABOW, Webbed Wing." },
    { city: "Mexico City", country: "Mexico", lat: 19.43, lng: -99.13, era: "current", note: "The bilingual psych-gaze wave moving north from Tijuana through Guadalajara." },
    { city: "San Francisco Bay", country: "USA", lat: 37.77, lng: -122.41, era: "second_wave", note: "Where blackgaze got invented; where Deafheaven made it canonical." },
    { city: "London", country: "UK", lat: 51.5, lng: -0.12, era: "first_wave", note: "Creation Records, 4AD, the press, the hostility, the legend." },
  ];

  return { MOOD_COLORS, MOOD_TO_BANDS, BANDS, BAND_MOODS, ERAS, SCENES };
})();
